name: Ejecutar en DEV_B

on:
  push:
    branches:
      - DevWF

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Imprimir mensaje
      run: echo "Se hizo push a la rama Develop para la rama Develop. Ejecutando flujo de trabajo..."
