name: Prueba Manual

on:
  workflow_dispatch:  # Disparador manual

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Imprimir mensaje
      run: echo "¡Hola! Este es un flujo de trabajo de prueba ejecutado manualmente."
    - name: Cat de arvhivo
      run: ls
      working-directory: ${{ github.workspace }}
